Parameters:

  VpcId:
    Type: AWS::EC2::VPC::Id

  SubnetId:
    Type: AWS::EC2::Subnet::Id

  AmiId:
    Type: AWS::EC2::Image::Id

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id

  InstanceType:
    Type: String
    Default: t3.micro

  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName


Resources:

  myInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPairName
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd