name: AWS CloudFormation Deploy/Destroy

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose Deploy or Destroy"
        required: true
        default: "deploy"
        type: choice
        options:
          - deploy
          - destroy

jobs:

  deploy:
    if: ${{ github.event.inputs.action == 'deploy' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Deploy CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file cloudformation.yml \
            --stack-name my-ec2-stack \
            --parameter-overrides \
              VpcId=${{ secrets.VPC_ID }} \
              SubnetId=${{ secrets.SUBNET_ID }} \
              AmiId=${{ secrets.AMI_ID }} \
              SecurityGroupId=${{ secrets.SECURITY_GROUP_ID }} \
              InstanceType=t3.micro \
              KeyPairName=${{ secrets.KEY_PAIR_NAME }}

  destroy:
    if: ${{ github.event.inputs.action == 'destroy' }}
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Destroy CloudFormation
        run: |
          aws cloudformation delete-stack \
            --stack-name my-ec2-stack

      - name: Wait for Stack Deletion
        run: |
          aws cloudformation wait stack-delete-complete \
            --stack-name my-ec2-stack